apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ceejaysay/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: ceejaysay/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.js"
            dest: .
    - image: ceejaysay/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: ceejaysay/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: ceejaysay/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    - image: ceejaysay/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
