name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: cd client && docker build -t ceejaysay/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ceejaysay/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: cd client && docker build -t ${{ secrets.REGISTRY_NAME }}/client .
      - run: doctl registry login
      - run: docker push ${{ secrets.REGISTRY_NAME }}/client
      - run: doctl kubernetes cluster kubeconfig save tickets
      - run: kubectl rollout restart deployment -n client-depl