# This is a basic workflow to help you get started with Actions final test

name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd orders && docker build -t ceejaysay/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ceejaysay/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: cd orders && docker build -t ${{ secrets.REGISTRY_NAME }}/orders .
      - run: doctl registry login
      - run: docker push ${{ secrets.REGISTRY_NAME }}/orders
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment -n orders-depl
