name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: cd auth && docker build -t ceejaysay/auth .
      - run: doctl registry login --expiry-seconds 1200
      - run: docker push ceejaysay/auth
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl