name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 98ca7e62-196d-4ed0-97bd-b794b1559638
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
