name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
